language: java
jdk:
- oraclejdk8
notifications:
  email: false
  slack:
    rooms:
      secure: vlZ2gySXLEpKJFvvg/Gss9voyQFy2PpID2e1S6cmgeE87qge756FP1AG0eaR+TEDVpe1rAx99OLT3Q08BxjzyJHUCVksxXmmqUuUYXi2mmP+IbEo89/vQ0l99ht03XfV2q6ZKHhd5uQCsj+U/vqj7NPM8PsN6rNyPLU1YfXOVQ1Mt5p8IzgQ1RbUXn7knaJeqbvj8Wxaa8KbDE4af8v58lT0d4UPuBaVccXaMuMNaQ9qXnezgGeK7bM2kfohPssrkp4zjFR5zJHgzgvioXY1ycI/F2hpJxoK+w5X4XX6FuGKl9sWJYAWevYvR7URbmzXn2aWY/TGcFr5iRnjr/EbWsoVr55iuw+diK3/qkEe/oL6gXUhLiEdGLTw+6gqF98iFIW5X3OHIKzfH6wF00hwGlnjhN7k7odjV07MMduPbURqRBPPUO03M5GTcrc4Os6y+cEH98Wkj8TQHPSLFwu9ly9xD1oZPnMp/hoM/4sxnIHW07zA3ZVsl3IbVeWfSbmwYU9RURgIaQVgTAehkGsQQXkvqkWTJVSAFOT3DuEoHcTLlJWTxAfpj5bXsJEnjjyBDYmxuVDp5cOFqN7KBUdwEy66lTfJVemMFMgGOYyuDDchGrB3kjkGozz/QbVF7L/Pw7Z6Zr/jbXHVvteL3zoC/B/XgCdpF4WWHXRIKsuSI44=
    on_success: change
    on_failure: always
addons:
  sonarqube:
    token:
      secure: Nu7+/lMt8SucdslH4K84xC7hGKvSB2H1TDW94kef3E+uzfuHhyYlAmRXfxMJiwAnvjvxe+v7yjgMU6SXyx9F1o9fRONYN9aGyYpwGWTkBkPN2ZKRLT9jqoBjaS88eL4fY1u5LxGikYiC7YHpgmCzj68mCR4ns2Ap6b3pGlkvYhsOVPi3flhdrD5zY2XpEAmxp9CseD12xGV1XVBbv9RIzYv96/Usnio3exAx5NaUZ/QHFrXUKMA17NiHesapJjcztZc5HvKKCHBlfDhS45F30lxLZl7ptAn9GJQZSNOjGCMNIvHQOCgja9KTbbJMQJ9AwT47dxKXmuOYuatStJHFqKM3z49sn/tTBeFEUGScLSobi5ikSRfbSHEngt/2Ujy5DaZTLG584k6DZE/10L+0Yv7Ae1oRp3LyFyMLZWlyzIovgRbf2acAj6WDYvRbTnphANFpkW/nzLmZldxm3qn+BD+5BLKMSVdgWtpsP2TzKvov86U1AXshsyecxtWSZFdh1qq1nnirWt1ysKnwvm6k/NOEJNdolzkLeF4FajUiMrZ60Wfbu6Y+U4zFEdIfLx1FwMgUJ25YhJ7PLmkR6HzPBHv5Ew5d6Lmwl0SgD8lYNIjwAjkIBE0T4us6JwIJ3lGXvQCouxAn6Ficzquo+PzHcejMh5irrzwp3Pd4RU8BbLI=